import type { NextPage } from "next";
import Head from "next/head";
import CategoryFilters from "../components/CategoryFilters";

import knex from "../knex";

const region = process.env.NEXT_PUBLIC_MY_AWS_REGION;
const bucket = process.env.NEXT_PUBLIC_MY_AWS_BUCKET;

type Props = { data: any };

const Home: NextPage<Props> = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-white">
          <div className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <CategoryFilters />

            <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {data.map(({ key }) => (
                <div key={key} className="group relative">
                  <div className="w-full min-h-80 bg-gray-200 rounded-md overflow-hidden">
                    <a
                      href={`https://${bucket}.s3.${region}.amazonaws.com/${key}`}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <img
                        src={`https://${bucket}.s3.${region}.amazonaws.com/${key}`}
                        className="hover:opacity-75 w-full h-full object-center object-cover lg:w-full lg:h-full"
                      />
                    </a>
                  </div>
                  <div className="flex justify-center mt-3 shadow-sm rounded-md">
                    <button
                      type="button"
                      className="inline-flex items-center px-4 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                    >
                      🍺&nbsp;&nbsp;Foaming
                    </button>
                    <button
                      type="button"
                      className="inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                    >
                      🧪&nbsp;&nbsp;Not Foaming
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const data = await knex("images").select("*").limit(8);

  return {
    props: { data },
  };
}
