import type { NextPage } from "next";
import Head from "next/head";

import knex from "../knex";

const region = process.env.NEXT_PUBLIC_MY_AWS_REGION;
const bucket = process.env.NEXT_PUBLIC_MY_AWS_BUCKET;

type Props = { data: any };

const Home: NextPage<Props> = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-white">
          <div className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h2 className="text-2xl font-extrabold tracking-tight text-gray-900">
              Reactor Images
            </h2>

            <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {data.map(({ key }) => (
                <div key={key} className="group relative">
                  <div className="w-full min-h-80 bg-gray-200 rounded-md overflow-hidden group-hover:opacity-75">
                    <img
                      src={`https://${bucket}.s3.${region}.amazonaws.com/${key}`}
                      className="w-full h-full object-center object-cover lg:w-full lg:h-full"
                    />
                  </div>
                  <div className="mt-4 flex justify-between">
                    <div>
                      <h3 className="text-sm text-gray-700">
                        <a
                          href={`https://${bucket}.s3.${region}.amazonaws.com/${key}`}
                        >
                          <span
                            aria-hidden="true"
                            className="absolute inset-0"
                          />
                          click
                        </a>
                      </h3>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const data = await knex("images").select("*").limit(10);
  console.log(data);

  return {
    props: { data },
  };
}
